[project]
user_env = []
session_timeout = 3600
user_session_timeout = 1296000
cache = false
persist_user_env = false
mask_user_env = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
assistant_message_autoscroll = true
auto_tag_thread = true
edit_message = true
allow_thread_sharing = false
favorites = false

[features.slack]
reaction_on_message_received = false

[features.spontaneous_file_upload]
    enabled = true
    accept = ["application/pdf", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.ms-excel"]
    max_files = 5
    max_size_mb = 20

[features.audio]
    enabled = false
    sample_rate = 24000

[features.mcp]
    enabled = false

[features.mcp.sse]
    enabled = true

[features.mcp.streamable-http]
    enabled = true

[features.mcp.stdio]
    enabled = true
    allowed_executables = [ "npx", "uvx" ]

[UI]
name = "Acreditaciones IA"
confirm_new_chat = true
cot = "full"
alert_style = "classic"
logo_file_url = ""
default_avatar_file_url = ""

[UI.theme]
default = "light"

    [UI.theme.light]
    background = "#FAFAFA"
    paper = "#FFFFFF"

        [UI.theme.light.primary]
        main = "#005BAB"
        dark = "#003F7A"
        light = "#4D8AC6"

[meta]
generated_by = "2.9.6"
